#!/bin/bash

BASENAME="$(basename $0)"

usage() {
    echo "Usage: $BASENAME [OPTION...]"
    echo
    echo "OPTIONS:"
    echo "  --no-push           Don't push local changes after syncing from the remote"
    echo "  --push-plugins      Commit and push local plugin configurations to remote"
    echo "                        instead of overwriting local with remote"
    echo "  -m <message>        Commit message (will be after the sync summary)"
    echo "  -h | --help         Display this message and exit"
}

has_autostash() {
    [[ "$(git stash list -n 1)" == "stash@{0}: autostash" ]]
}

push_plugins=1
push_changes=0
message=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --no-push)
            push_changes=1
            shift
            ;;
        --push-plugins)
            push_plugins=0
            shift
            ;;
        -m)
            message="$2"
            shift 2
            ;;
        -*|--*)
            >&2 echo "$BASENAME: Unknown option '$1'"
            usage
            exit 1
            ;;
        *)
            >&2 echo "$BASENAME: Unexpected positional argument '$1'"
            usage
            exit 1
            ;;
    esac
done

echo "Syncing process:"
echo "================"
echo "- Backup local changes"
echo "- Pull changes from the remote (GitHub)"
echo "- Incorporate local changes with new changes from the remote"
if [[ $push_changes -eq 0 ]]; then
    echo -n "- Push local changes to the remote"
    if [[ $push_plugins -eq 0 ]]; then
        echo -n " (including plugin configuration data)"
    fi
    echo ""
fi
echo "- Delete backup"
echo ""


if [[ $push_plugins -ne 0 ]]; then
    git restore --staged --worktree -- content/.obsidian/plugins/
fi

if [[ ! `git status --porcelain --untracked-files=no` ]]; then
    echo "No local changes; just pulling from remote"
    git pull
    exit $?
fi

echo ""
echo "Attempting to Backup -> Pull -> Incorporate local changes"
echo ""

# Automatically stash local changes and pop them after a successful pull.
# This could result in a merge conflict, but in typical scenarios it won't.
git pull --autostash
if [[ $? -ne 0 ]]; then
    >&2 echo ""
    >&2 echo " !! ERROR DETECTED !!"
    >&2 echo "======================"
    >&2 echo "You may have gotten a merge conflict in the process of incorporating local changes."
    >&2 echo "If so, you will need to resolve these conflicts using normal git process."
    >&2 echo "If you are a non-compsci user, ping Joseph in the group chat for help!"
    exit 1
fi

if [[ $push_changes -ne 0 ]]; then
    echo "Sync successful"
    exit 0
fi

echo ""
echo "Attempting to Commit -> Push -> Delete backup"
echo ""

# Construct commit message
if [[ -n "$message" ]]; then
    message=$(printf "\n\n$message")
fi
message="Sync by $(git config user.name) on $(date "+%B %-d, %Y at %-I:%M %p (%Z)")$message"

# Perform commit
git add . && \
    git commit -m "$message" && \
    git push
if [[ $? -eq 0 ]] && has_autostash; then
    echo "Sync successful. Deleting backup."
    git stash drop
fi

echo ""

