#!/bin/bash

BASENAME="$(basename $0)"

usage() {
    echo "Usage: $BASENAME [OPTION...]"
    echo
    echo "OPTIONS:"
    echo "  --push-plugins      Commit and push local plugin configurations to remote"
    echo "                        instead of overwriting local with remote"
    echo "  -m <message>        Commit message (will be after the sync summary)"
    echo "  -h | --help         Display this message and exit"
}

push_plugins=1
message=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        -h|--help)
            usage
            exit 0
            ;;
        --push-plugins)
            push_plugins=0
            shift
            ;;
        -m)
            message="$2"
            shift 2
            ;;
        -*|--*)
            >&2 echo "$BASENAME: Unknown option '$1'"
            usage
            exit 1
            ;;
        *)
            >&2 echo "$BASENAME: Unexpected positional argument '$1'"
            usage
            exit 1
            ;;
    esac
done


if [[ $push_plugins -eq 0 ]]; then
    echo "Pushing local plugin configurations to the remote"
else
    echo "Overwriting local plugin configurations with the remote..."
    git restore --staged --worktree -- content/.obsidian/plugins/
fi

if [[ ! `git status --porcelain --untracked-files=no` ]]; then
    echo "No local changes; just pulling from remote"
    git pull
    exit $?
fi

echo ""
echo "Attempting to Backup and Pull"
echo ""

git pull --autostash
if [[ $? -ne 0 ]]; then
    >&2 echo ""
    >&2 echo " !! ERROR DETECTED !!"
    >&2 echo "======================"
    >&2 echo "You may have gotten a merge conflict in the process of incorporating local changes."
    >&2 echo "If so, you will need to resolve these conflicts using normal git process."
    >&2 echo "If you are a non-compsci user, ping Joseph in the group chat for help!"
    exit 1
fi

echo ""
echo "Attempting to Incorporate local changes -> Commit -> Push -> Delete backup"
echo ""

# Construct commit message
if [[ -n "$message" ]]; then
    message=$(printf "\n\n$message")
fi
message="Sync by $(git config user.name) on $(date "+%B %-d, %Y at %-I:%M %p (%Z)")$message"

# Perform commit
git add . && \
    git commit -m "$message" && \
    git push
if [[ $? -eq 0 ]] && [[ "$(git stash list -n 1)" == "stash@{0}: autostash" ]]; then
    echo "Backup -> Pull -> Incorporate local changes -> Commit -> Push was successful. Deleting backup."
    git stash drop
fi

